### ISSUE TITLE
Single Fieldmap PAR file 

### ISSUE THREAD

**Issue by LexHayes** [Donders-Institute/bidscoin#61] opened 2021-01-28 15:34 UTC
Hi,

I have data that was collected about five years ago across three sites.
Two of the sites outputted DICOM files and one outputted PAR files. I've managed to convert the DICOM files into BIDS format and bidscoin has been extremely helpful for converting the PAR/REC files.
I do have one issue though that I so far have been unable to solve and was wondering if anyone had any insight/had come across this before.
I have a single PAR/REC file pair for the Fieldmap images. Looking at the PAR header they only have one echo but the PAR file does report two image types (0 = magnitude and 3 = phase diff). I've noticed for the DICOMs you can add in image type which would be helpful for my bids mapping here, is this a functionality for the PAR files as well?

I am currently getting this error when converting my files;

2021-01-28 14:53:36 - bidscoin - WARNING Empty 'IntendedFor' fieldmap value in /Volumes/toshiba/DICOMS/BIDS/sub-3002/ses-1/fmap/sub-3002_ses-1_phasediff.json: the IntendedFor value of the bidsmap entry was empty
2021-01-28 14:53:36 - bidscoin - ERROR Could not find expected magnitude1 image associated with: /Volumes/toshiba/DICOMS/BIDS/sub-3002/ses-1/fmap/sub-3002_ses-1_phasediff.json
2021-01-28 14:53:36 - bidscoin - ERROR Could not find expected magnitude2 image associated with: /Volumes/toshiba/DICOMS/BIDS/sub-3002/ses-1/fmap/sub-3002_ses-1_phasediff.json
2021-01-28 14:53:36 - bidscoin - ERROR Cannot find and add valid EchoTime1=None and EchoTime2=None data to: /Volumes/toshiba/DICOMS/BIDS/sub-3002/ses-1/fmap/sub-3002_ses-1_phasediff.json

Thanks!

**Comment by marcelzwiers** [comment] 2021-01-28 16:07
Hi Lex, thanks for your feedback. I don't have any PAR/REC fieldmap data or knowledge about them, but I can try and fix it for you. Fieldmaps are quite tricky, and what happens here is that you said you had a phasediff image and then the bidscoiner looked for the associated magnitude image (there should be at least one, see [here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-image-and-at-least-one-magnitude-image). But it can't find it. So my question is, do you have such magnitude images and/or can you perhaps share your `bidsmap.yaml` file with me?

**Comment by LexHayes** [comment] 2021-01-28 16:52
Hi Marcel,

Thanks for your quick response!
In the raw data set I only have one Fieldmap PAR/REC file. However when I have looked in the PAR header it does have the two sets of 33 slices one set is labelled as image type 0 and the other as image type 3 which I believe is magnitude and phasediff respectively?

I've attached my bidsmap.yaml file as well.

Thanks
[bidsmap.txt](https://github.com/Donders-Institute/bidscoin/files/5888771/bidsmap.txt)

**Comment by marcelzwiers** [comment] 2021-01-29 07:57
Yes, but after conversion of the PAR/REC file there doesn't seem to be a phase image, according to `bidscoiner`. That is probably because the output filename is different than expected. Or because dcm2niix doesn't convert the PAR/REC file properly. So could you tell me the filenames of the fmap files in `BIDS/sub-3002/ses-1/fmap`?

**Comment by LexHayes** [comment] 2021-02-01 12:26
Hi Marcel, no you are correct there his not a specific phase image produced - I have attached a screenshot of the images that are produced, hope this is helpful!
<img width="296" alt="Screenshot 2021-02-01 at 12 18 50" src="https://user-images.githubusercontent.com/72872065/106458438-4ae84d00-6488-11eb-9edd-2deb6a44e623.png">

**Comment by marcelzwiers** [comment] 2021-02-10 09:46
So if I understand it correctly, you have acquired two fieldmaps (one with `acq-PHO01 and one without)? What I need to know in order to fix things is what the exact output is of dcm2niix. Can you call it directly for me and tell me what it produced? Also, if you send me the `BIDS/code/bidscoin/bidscoiner.log`, that could perhaps be useful too

**Comment by LexHayes** [comment] 2021-02-10 11:08
Sure! When I call dcm2niix directly it produces the following files for the input file sub-3002_fmap.PAR/REC;
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>_ph.json
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>_ph.nii.gz
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>_pha.json
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>_pha.nii.gz
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>.json
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>.nii.gz
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>.json
sub-3002_<protocol_name>_<examination_date/time>_<acquisition_number>.nii.gz

I have also sent you the bidscoiner.log file.

Many thanks for your support!

**Comment by marcelzwiers** [comment] 2021-02-10 12:26
Btw, I see that you removed the `run-<<1>>` index. This is generally not advisable, as this runindex is used to account for multiple acquisitions. In your case dcm2niix produces two phase images that are now both written by bidscoiner to the same `acq-PH00` image. I will try and see if I can easily catch these fieldmaps in my code (the combination of fieldmaps and dcm2niix is tricky).

**Comment by marcelzwiers** [comment] 2021-02-10 12:30
I am also a bit confused because your logs show DICOM data from Toshiba but we are discussing PAR/REC data from Philips

**Comment by LexHayes** [comment] 2021-02-10 12:34
Hi,

Yes toshiba is the name of the hard-drive that the data is stored on and the folder 'DICOMS' is named as such because I have data from three different sites two of which produced DICOMS and one produced PAR/REC

**Comment by marcelzwiers** [comment] 2021-02-10 12:41
Have you tried using the `magnitude` suffix instead of `fieldmap`? Because I suspect that your PAR/REC output is not a fieldmap but one magnitude- and two phase-images? That may perhaps solve your problem?

**Comment by LexHayes** [comment] 2021-02-10 14:06
Ah yes thank you this now appends 'magnitude' or 'phase' onto the output files as shown below;
<img width="313" alt="Screenshot 2021-02-10 at 13 58 31" src="https://user-images.githubusercontent.com/72872065/107519591-5b937400-6ba8-11eb-8738-72526c47db30.png">
however there is still the 'acq-PHO01' label present despite this not being specified?
Similarly this is happening with my functional runs for which I have two echos per task per run and the converted files are being named;
<subject>_<session>_acq-E0*_<task>_<run>_bold.nii.gz/json
I notice with DICOM data there is an EchoTime attribute number which would allow me to distinguish between the echos, is this something that is possible with PAR/REC files as well?

**Comment by marcelzwiers** [comment] 2021-02-10 15:39
I'll take a look at it that because it should go in the echo entity. As for your functional scans, this is the desired behaviour because BIDS 1.4.1 does not provide an echo entity for functional scans (therefore I appended the echo info to the acquisition entity). The upcoming BIDS 1.5 does provide for this and you can give it a try by installing the latest / development bidscoin version:
```console
pip install git+https://github.com/Donders-Institute/bidscoin
```

**Comment by marcelzwiers** [comment] 2021-02-10 17:28
I just committed an experimental fix for your fieldmaps in the latest bidscoin version

**Comment by LexHayes** [comment] 2021-02-11 12:04
Thanks for taking a look at that. I've just installed the latest experimental version and tried to re-run bids mapper. The gui opens fine but when I try to click on any of the 'edit' buttons I get the following error;

  File "/Users/ah2816/opt/anaconda3/envs/Python/lib/python3.8/site-packages/bidscoin/bidseditor.py", line 980, in get_allowed_suffixes
    for run in runs:
TypeError: 'NoneType' object is not iterable
Abort trap: 6

**Comment by marcelzwiers** [comment] 2021-02-11 12:20
I see, shouldn't happen but I can't reproduce it here. Did you start with a clean bids output directory? What template did you use? The standard one or the `bidsmap_dccn` one? If you made your own template, can you perhaps then share it with me?

**Comment by marcelzwiers** [comment] 2021-02-11 12:38
I made a tiny tweak in the code (4926f8bb570da72fab5ce643ffad2e9d5738d772) maybe that helps...

**Comment by LexHayes** [comment] 2021-02-12 11:53
My bids output directory is clean and I made my own template which I have attached 
[bidsmap.yaml.zip](https://github.com/Donders-Institute/bidscoin/files/5971539/bidsmap.yaml.zip)

**Comment by marcelzwiers** [comment] 2021-02-12 16:25
Sorry, I noticed that the `pip install git+https://github.com/Donders-Institute/bidscoin` was a bit broken. Should work much better now :-)

**Comment by marcelzwiers** [comment] 2021-02-12 16:50
You made that template with a text editor?

**Comment by marcelzwiers** [comment] 2021-02-12 16:53
The idea of a template is that it works for a collection / variety of studies, as a starting point. So the attributes should be as generic as possible, so that it will work for more studies. The study specific attibutes and bids-labels are then added by the bidsmapper+bidseditor and saved in the study folder as a (study specific) bidsmap.yaml file. Your custom bidsmap, seems a bit like neither?

**Comment by marcelzwiers** [comment] 2021-02-15 11:52
I cannot exactly reproduce your error here
1. Do you get the error when you, for example, use the `-t bidsmap_dccn` option?
2. Do you still get the error with your custom template when you use the latest code (i.e. after `pip install --upgrade git+https://github.com/Donders-Institute/bidscoin`)?

**Comment by LexHayes** [comment] 2021-02-17 10:35
Hi

Yes with the latest code this seems to have solved the issue! Thanks for your help!

**Closed** 2021-02-17 10:44 UTC
