### ISSUE TITLE
KeyError when run without making any changes

### ISSUE THREAD

**Issue by dmd** [Donders-Institute/bidscoin#152] opened 2022-09-13 15:15 UTC
I'm sure I'm doing something wrong, but if I simply run bidsmapper, accept the defaults, then bidscoiner, I get:

```
2022-09-13 11:12:45 - INFO | No bidscoin.plugin.spec2nii2bids sourcedata found in: /in/sub-001
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 3629, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'fmap/sub-001_acq-rsgrefieldmap_run-1_magnitude1_e1.nii.gz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bidscoiner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidscoiner.py", line 366, in main
    bidscoiner(rawfolder    = args.sourcefolder,
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidscoiner.py", line 197, in bidscoiner
    addmetadata(bidssession, subid, sesid)
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidscoiner.py", line 263, in addmetadata
    acqtime    = scans_table.loc[fmap, 'acq_time']
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 960, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/frame.py", line 3622, in _get_value
    row = self.index.get_loc(index)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 3631, in get_loc
    raise KeyError(key) from err
KeyError: 'fmap/sub-001_acq-rsgrefieldmap_run-1_magnitude1_e1.nii.gz'
```

**Comment by marcelzwiers** [comment] 2022-09-26 11:37
It is caused by an unexpected fieldmap filename (i.e. it has a dcm2niix `_e1` suffix), however, in a different context I already submitted a commit (438b8a085ef8b0f2b3a70a6db6f6e8d22cb7917b) that should catch such exceptions. So the latest version should not crash, but the underlying problem remains, namely the fact that your fieldmaps are stored in a way unknown to BIDScoin. What kind of sequence is it? (e.g. GE, Philips or Siemens? Are the magnitude 1 / 2, phasediff all stored in the same sequence folder?)

**Comment by marcelzwiers** [comment] 2022-09-26 12:39
To help me trace this down, can you perhaps share your logfile with me?

**Comment by dmd** [comment] 2022-09-28 19:35
[bidscoin.zip](https://github.com/Donders-Institute/bidscoin/files/9668423/bidscoin.zip)

**Comment by marcelzwiers** [comment] 2022-09-29 08:24
Strange, your fieldmap seems to be recognised just fine, but the code that should strip off the dcm2niix `_e1` postfix is not being executed because the search for such files fail, i.e. in your case this glob search seems to be empty:
```python
outfolder=Path('/out/sub-001/fmap')
bidsname='sub-001_acq-rsgrefieldmap_run-1_magnitude1'
dcm2niixpostfix='_e'
outfolder.glob(f"{bidsname}*{dcm2niixpostfix}*.nii*" 
```
Or perhaps even:
```python
outfolder.glob(f"{bidsname}.nii*"
```
I don't understand how this can be possible, is  `/out` a rootfolder?

Btw, in your bidsmap [Options] you can remove the `module add dcm2niix;` part of the command string.

**Comment by marcelzwiers** [comment] 2022-10-03 09:23
I really don't see any lead to solve your issue. I can try to reproduce it if you share a data sample?

**Comment by dmd** [comment] 2022-10-03 12:33
Is there a particular file that would be of use?

```
/data/ddrucker/bidssing
├── code
│   └── bidscoin
│       ├── bidscoiner.errors
│       ├── bidscoiner.log
│       ├── bidsmapper.errors
│       ├── bidsmapper.log
│       └── bidsmap.yaml
├── dataset_description.json
├── participants.tsv
├── README
└── sub-001
    ├── anat
    │   ├── sub-001_acq-T1MEMPRAGE64chRMS_run-1_T1w.json
    │   ├── sub-001_acq-T1MEMPRAGE64chRMS_run-1_T1w.nii.gz
    │   ├── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e1.json
    │   ├── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e1.nii.gz
    │   ├── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e2.json
    │   ├── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e2.nii.gz
    │   ├── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e3.json
    │   ├── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e3.nii.gz
    │   ├── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e4.json
    │   └── sub-001_acq-T1MEMPRAGE64ch_run-1_T1w_e4.nii.gz
    ├── dwi
    │   ├── sub-001_acq-dMRIdir99AP_run-1_dwi.bval
    │   ├── sub-001_acq-dMRIdir99AP_run-1_dwi.bvec
    │   ├── sub-001_acq-dMRIdir99AP_run-1_dwi.json
    │   ├── sub-001_acq-dMRIdir99AP_run-1_dwi.nii.gz
    │   ├── sub-001_acq-dMRIdir99PA_run-1_dwi.bval
    │   ├── sub-001_acq-dMRIdir99PA_run-1_dwi.bvec
    │   ├── sub-001_acq-dMRIdir99PA_run-1_dwi.json
    │   └── sub-001_acq-dMRIdir99PA_run-1_dwi.nii.gz
    ├── extra_data
    │   ├── sub-001_acq-dMRIdir99AP_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-dMRIdir99APSBRef_echo-1_EP.json
    │   ├── sub-001_acq-dMRIdir99AP_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-dMRIdir99APSBRef_echo-1_EP.nii.gz
    │   ├── sub-001_acq-dMRIdir99PA_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-dMRIdir99PASBRef_echo-1_EP.json
    │   ├── sub-001_acq-dMRIdir99PA_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-dMRIdir99PASBRef_echo-1_EP.nii.gz
    │   ├── sub-001_acq-pdt2tsetra_rec-2DORIGINALPRIMARYMNDNORM_run-1_mod-pdt2tsetra_echo-1_SE_e1.json
    │   ├── sub-001_acq-pdt2tsetra_rec-2DORIGINALPRIMARYMNDNORM_run-1_mod-pdt2tsetra_echo-1_SE_e1.nii.gz
    │   ├── sub-001_acq-pdt2tsetra_rec-2DORIGINALPRIMARYMNDNORM_run-1_mod-pdt2tsetra_echo-1_SE_e2.json
    │   ├── sub-001_acq-pdt2tsetra_rec-2DORIGINALPRIMARYMNDNORM_run-1_mod-pdt2tsetra_echo-1_SE_e2.nii.gz
    │   ├── sub-001_acq-slicepositioning22degreeangle_rec-2DORIGINALPRIMARYMMBNDNORMMOSAIC_run-1_mod-slicepositioning22degreeangle_echo-1_EP.json
    │   ├── sub-001_acq-slicepositioning22degreeangle_rec-2DORIGINALPRIMARYMMBNDNORMMOSAIC_run-1_mod-slicepositioning22degreeangle_echo-1_EP.nii.gz
    │   ├── sub-001_acq-SpinEchoFieldMapAP_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-SpinEchoFieldMapAP_echo-1_EP.json
    │   ├── sub-001_acq-SpinEchoFieldMapAP_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-SpinEchoFieldMapAP_echo-1_EP.nii.gz
    │   ├── sub-001_acq-SpinEchoFieldMapPA_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-SpinEchoFieldMapPA_echo-1_EP.json
    │   ├── sub-001_acq-SpinEchoFieldMapPA_rec-2DORIGINALPRIMARYMNDMOSAIC_run-1_mod-SpinEchoFieldMapPA_echo-1_EP.nii.gz
    │   ├── sub-001_acq-T2SPACEgr2_rec-3DORIGINALPRIMARYMNDNORM_run-1_mod-T2SPACEgr2_echo-1_SE.json
    │   ├── sub-001_acq-T2SPACEgr2_rec-3DORIGINALPRIMARYMNDNORM_run-1_mod-T2SPACEgr2_echo-1_SE.nii.gz
    │   ├── sub-001_acq-t2tsedarkfluidtra_rec-2DORIGINALPRIMARYMNDNORM_run-1_mod-t2tsedarkfluidtra_echo-1_SEIR.json
    │   └── sub-001_acq-t2tsedarkfluidtra_rec-2DORIGINALPRIMARYMNDNORM_run-1_mod-t2tsedarkfluidtra_echo-1_SEIR.nii.gz
    ├── fmap
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e1.json
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e1.nii.gz
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e2.json
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e2.nii.gz
    │   ├── sub-001_acq-rsgrefieldmap_run-1_phasediff_e2_ph.json
    │   └── sub-001_acq-rsgrefieldmap_run-1_phasediff_e2_ph.nii.gz
    ├── func
    │   ├── sub-001_task-restingstate_run-1_echo-1_bold_pha.json
    │   ├── sub-001_task-restingstate_run-1_echo-1_bold_pha.nii.gz
    │   ├── sub-001_task-restingstate_run-1_echo-1_bold_ph.json
    │   ├── sub-001_task-restingstate_run-1_echo-1_bold_ph.nii.gz
    │   ├── sub-001_task-rest_run-1_echo-1_bold.json
    │   ├── sub-001_task-rest_run-1_echo-1_bold.nii.gz
    │   ├── sub-001_task-rest_run-2_echo-1_bold.json
    │   └── sub-001_task-rest_run-2_echo-1_bold.nii.gz
    └── sub-001_scans.tsv

8 directories, 59 files
```

**Comment by marcelzwiers** [comment] 2022-10-03 12:49
```
   ├── fmap
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e1.json
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e1.nii.gz
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e2.json
    │   ├── sub-001_acq-rsgrefieldmap_run-1_magnitude1_e2.nii.gz
    │   ├── sub-001_acq-rsgrefieldmap_run-1_phasediff_e2_ph.json
    │   └── sub-001_acq-rsgrefieldmap_run-1_phasediff_e2_ph.nii.gz
```
This should not be there as it is, the dcm2niix e1/e2 suffix should have been stripped off by bidscoin (in the lines depicted above), but somehow they aren't

**Comment by marcelzwiers** [comment] 2022-10-03 12:55
What I would need to test this is the raw DICOM data (I understand this may pose a data-sharing problem). I am really puzzled about it

**Comment by marcelzwiers** [comment] 2022-10-19 17:07
Good news: The DICOM sorting issue was fixed with the latest commit (8f69b2301dcd5e055d615e0eb3eecf05d30542ab)
Bad news: I could not reproduce your issue with your data (i.e. it works normally here). So I suppose it must be a subtle library version problem somewhere. What python version are you using?

**Comment by dmd** [comment] 2022-10-19 17:14
If it works in Singularity I'd be happy to do it within a container (I generally prefer that anyway).

**Comment by dmd** [comment] 2022-10-19 17:29
```
ddrucker@micc ~ via 🐍 v3.9.7 (bidscoin)
$ pip list
Package          Version
---------------- --------
bidscoin         3.7.3
coloredlogs      15.0.1
cycler           0.11.0
fonttools        4.37.1
humanfriendly    10.0
kiwisolver       1.4.4
matplotlib       3.5.3
multiecho        0.28
nibabel          4.0.2
numpy            1.23.3
packaging        21.3
pandas           1.4.4
Pillow           9.2.0
pip              21.2.3
pydicom          2.3.0
pyparsing        3.0.9
PyQt5            5.14.0
PyQt5-Qt5        5.15.2
PyQt5-sip        12.11.0
python-dateutil  2.8.2
pytz             2022.2.1
ruamel.yaml      0.17.21
ruamel.yaml.clib 0.2.6
setuptools       57.4.0
six              1.16.0
tqdm             4.64.1
```

**Comment by marcelzwiers** [comment] 2022-10-19 17:38
Nothing to see there... Is the path to your bids output folder somehow unusual (some symbolic links in there, or is it on an unusual mount, or may there be something else that could confuse the pathlib library?

**Comment by marcelzwiers** [comment] 2022-10-19 23:58
I figured it out, it's an installation error after all: the `module add dcm2niix` raised an error after which a check was done for dcm2niix output. There was a bug in there that didn't account for the additional `_e1` suffixes. So you should remove the `module add ..` substring in your bidsmap Options, or upgrade your bidscoin install to the latest github commit

**Closed** 2022-10-20 00:42 UTC
Labels: bug
