### ISSUE TITLE
Gradientfieldmap (phasediff) problem with TE and „:“ error in bidsmap.yaml file

### ISSUE THREAD

**Issue by karl-koschutnig** [Donders-Institute/bidscoin#41] opened 2019-07-11 16:09 UTC
Thanks for helping me with the „SpacingBetweeSlices“ Problem - super fast;-)

I just wanted to give you a short feedback about a few problems I had using the updated version (I found a work-around for me - so I just wanted you to give the info)

1) I tried to bring a gradientfieldmap into the bids-format. Acquired on Siemens the output is magnitude1, magnitude2 and phasediff. Problem was that the EchoTime of the first magnitude was not correctly written into the .json file of the phasediff (TE1= null) I think there might be a problem with indexing the Echotimes? Echtime2 (from magnitude2) was correctly written.
2)  I found out that it is a requirement to have the „run-x“ in the fieldmap . If you don’t define „run“ - intendedfor will not work.
3) After using the bidseditor I found that at the very end of the .ymal-file (Section Filesystem) participants: and session: were written in the same line. I had to put „session:“ into the next line and everything went smoothly. 

Best,
Karl

**Comment by marcelzwiers** [comment] 2019-07-11 18:02
Hi Karl,

Is that with the version I released a few hours ago? That would be super
fast! ;-)

Thanks for your feedback, here is what I can say about it now (I'm leaving
for holidays tomorrow):

   1. I'll look into it, it is a bit of a tricky problem because Siemens
   often (always?) writes both magnitude images into the same series. dcm2niix
   then produces two images for one series, whereas normally it onlly produces
   one image per series. I then fix this in the code by retrospectively
   searching for a magnitude2 image, then adding the TE's to it. It's possibly
   that a TE is lost there, I'll check..
   2. the run:<<1>> is something you normally shouldn't touch. The double
   brackets make it a dynamic label, meaning it will get incremented (from 1)
   during bidscoiner runtime if there already exists a file with run-1. Did
   you have problems with leaving <<1>> as it was? The IntendedFor searches
   for bidsnames after all files are converted to nifti, so it should pick up
   all the runs (unless you specify a run-index in your IntendedFor search
   term (like IntendedFor: <<bold><run-1>>
   3. That is a problem of the ruamel library that I use to read and write
   yaml-files. You still have that problem with v2.2? I believe it's caused by
   the comments in the file and I worked around it by moving the Plugin
   section to the top. That worked very well for me, but maybe I should drop
   yaml and move to json if these problems remain (or wait for a better yaml
   library)

Cheers,
Marcel

Op do 11 jul. 2019 om 18:09 schreef karl-koschutnig <
notifications@github.com>:

**Comment by marcelzwiers** [comment] 2019-07-30 13:18
>     1. I tried to bring a gradientfieldmap into the bids-format. Acquired on Siemens the output is magnitude1, magnitude2 and phasediff. Problem was that the EchoTime of the first magnitude was not correctly written into the .json file of the phasediff (TE1= null) I think there might be a problem with indexing the Echotimes? Echtime2 (from magnitude2) was correctly written.

This should be fixed now in commit 3670aa291a9cbbd09680d6d38bd35efd2bbf51fd
(You can test this using pip install git+https://github.com/Donders-Institute/bidscoin)

**Comment by marcelzwiers** [comment] 2019-07-31 16:28
>     2. I found out that it is a requirement to have the „run-x“ in the fieldmap . If you don’t define „run“ - intendedfor will not work.
I think you may have entered non-BIDS compliant characters in your labels. I have now added some additional checks for this

**Comment by marcelzwiers** [comment] 2019-07-31 17:47
>     3. After using the bidseditor I found that at the very end of the .ymal-file (Section Filesystem) participants: and session: were written in the same line. I had to put „session:“ into the next line and everything went smoothly.
Which version of ruamel.yaml are you using? Can you run `pip search ruamel.yaml` for me?

**Closed** 2019-09-11 17:20 UTC
Labels: bug, duplicate
